name: Build and Deploy to Main

on:
    push:
        branches: [main] # Triggers ONLY on the main branch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                  node-version: "25.9"

            - name: Install and Build
              run: |
                  npm ci
                  npm run build

            - name: Deploy to Test Environment
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  protocol: ftps # secure ftp
                  local-dir: ./build/
                  server-dir: /zfk-hb.de/httpdocs/public/build/ # Main folder
